services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eduagent_backend
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: eduagent_frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8000 # Para que el rewrite de Next.js encuentre el backend en la red de Docker
    # env_file:
    #   - ./frontend/.env.local
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - frontend
      - backend
