"""EduAgent — Callback Router: endpoints for n8n to notify backend of completed tasks."""

import logging
from fastapi import APIRouter, HTTPException, Header
from pydantic import BaseModel
from typing import Optional
from app.config import get_settings
from app.services.supabase_service import supabase_service

router = APIRouter()
logger = logging.getLogger(__name__)
settings = get_settings()


def _verify_secret(x_n8n_secret: Optional[str]) -> None:
    """Verify the shared webhook secret to ensure the caller is n8n."""
    expected = settings.n8n_webhook_secret
    if expected and x_n8n_secret != expected:
        raise HTTPException(status_code=403, detail="Invalid webhook secret.")


# ---- Schemas ----

class VectorizacionCallback(BaseModel):
    documento_id: str
    chunks_count: Optional[int] = None
    success: bool = True
    error: Optional[str] = None


class EvaluacionCallback(BaseModel):
    evaluacion_id: str
    nota: Optional[float] = None
    retroalimentacion: Optional[str] = None
    procesado_correctamente: bool = True
    error_ocr: Optional[str] = None


# ---- Endpoints ----

@router.post("/vectorizacion-completada")
async def vectorizacion_completada(
    body: VectorizacionCallback,
    x_n8n_secret: Optional[str] = Header(default=None),
):
    """
    Called by n8n after the PDF ingestion workflow finishes.
    Updates documentos.vectorizado = true.
    """
    _verify_secret(x_n8n_secret)

    if not body.success:
        logger.error(
            f"Vectorización failed for documento {body.documento_id}: {body.error}"
        )
        await supabase_service.update_documento_vectorizado(
            body.documento_id, vectorizado=False
        )
        return {"status": "error_recorded", "documento_id": body.documento_id}

    # Link any orphaned document_chunks generated by n8n to this document
    linked_chunks = await supabase_service.link_document_chunks(body.documento_id)
    logger.info(f"Linked {linked_chunks} chunks to documento {body.documento_id}")

    ok = await supabase_service.update_documento_vectorizado(
        body.documento_id, vectorizado=True
    )
    if not ok:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to update documento {body.documento_id}",
        )

    logger.info(
        f"Documento {body.documento_id} vectorizado ✅ "
        f"({body.chunks_count or '?'} chunks)"
    )
    return {
        "status": "ok",
        "documento_id": body.documento_id,
        "chunks_count": body.chunks_count,
    }


@router.post("/evaluacion-completada")
async def evaluacion_completada(
    body: EvaluacionCallback,
    x_n8n_secret: Optional[str] = Header(default=None),
):
    """
    Called by n8n after the Gemini Vision evaluation workflow finishes.
    Updates evaluaciones with nota, retroalimentación and processing status.
    """
    _verify_secret(x_n8n_secret)

    update_data: dict = {
        "procesado_correctamente": body.procesado_correctamente,
    }
    
    eval_data = await supabase_service.get_evaluacion(body.evaluacion_id)
    if eval_data and eval_data.get("calificacion_manual"):
        # If already manually graded, only save the AI's grade in nota_ia for reference
        if body.nota is not None:
            update_data["nota_ia"] = body.nota
    else:
        if body.nota is not None:
            update_data["nota"] = body.nota
            update_data["nota_ia"] = body.nota
        if body.retroalimentacion is not None:
            update_data["retroalimentacion"] = body.retroalimentacion
        if body.error_ocr is not None:
            update_data["error_ocr"] = body.error_ocr

    result = await supabase_service.update_evaluacion(body.evaluacion_id, update_data)
    if result is None:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to update evaluacion {body.evaluacion_id}",
        )

    logger.info(
        f"Evaluación {body.evaluacion_id} procesada ✅ — "
        f"nota={body.nota}, ok={body.procesado_correctamente}"
    )
    return {
        "status": "ok",
        "evaluacion_id": body.evaluacion_id,
        "nota": body.nota,
        "procesado_correctamente": body.procesado_correctamente,
    }
